sylius_admin_customer:
    resource: |
        alias: sylius.customer
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_customer
        vars:
            all:
                header: toro.ui.customers
                templates:
                    form: ToroCoreBundle:Admin/Customer:_form.html.twig
            index:
                icon: ti-user
    type: sylius.resource
