toro_admin_post:
    resource: "@ToroCoreBundle/Resources/config/routing/admin/post.yml"

toro_admin_post_tag:
    resource: "@ToroCoreBundle/Resources/config/routing/admin/post_tag.yml"

toro_admin_post_flagged_type:
    resource: "@ToroCoreBundle/Resources/config/routing/admin/post_flagged_type.yml"
