toro_admin_cms_post_update_flags:
    path: /posts/{id}/update-flags
    methods: [GET, PATCH]
    defaults:
        _controller: toro.controller.post:updateAction
        _sylius:
            redirect: referer
            template: "@ToroCore/Post/_form_update_flags.html.twig"
            form:
                type: Toro\Bundle\CoreBundle\Form\Type\PostFlaggedUpdateType

toro_admin_post:
    resource: |
        alias: toro.post
        section: admin
        templates: ToroCoreBundle:PostCrud
        except: ['show']
        redirect: update
        grid: toro_admin_core_post
        vars:
          index:
            icon: ti-book
    type: sylius.resource

toro_admin_partial_post_taxon_filter:
    path: /_partial/posts/filter/taxon/{code}
    methods: [GET]
    defaults:
        code: "%toro_post_taxon_root%"
        _controller: sylius.controller.taxon:showAction
        _sylius:
            template: "@ToroCore/Post/_partial_taxon_filter.html.twig"
            repository:
                method: findOneByCode
                arguments: [ $code ]
