toro_admin_post_flagged_type:
    resource: |
        alias: toro.post_flagged_type
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show', 'delete']
        redirect: index
        grid: toro_admin_post_flagged_type
        vars:
          all:
            templates:
                form: "@ToroCore/PostFlaggedType/_form.html.twig"
          index:
            icon: ti-book
    type: sylius.resource

toro_admin_partial_post_flagged_type_filter:
    path: /_partial/posts/filter/flags
    methods: [GET]
    defaults:
        _controller: toro.controller.post_flagged_type:indexAction
        _sylius:
            template: "@ToroCore/PostFlaggedType/_partial_filter.html.twig"
            repository: findAll
