sylius_grid:
    grids:
        sylius_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.customer.class%"
            sorting:
                createdAt: desc
            fields:
                firstName:
                    type: string
                    label: toro.ui.first_name
                lastName:
                    type: string
                    label: toro.ui.last_name
                email:
                    type: string
                    label: toro.ui.email
                createdAt:
                    type: datetime
                    label: toro.ui.registration_date
                    options:
                        format: d-m-Y H:i
                confirmed:
                    type: twig
                    label: toro.ui.confirmed
                    path: .
                    options:
                        template: ToroCoreBundle:Admin/Customer/Field:confirmed.html.twig
            filters:
                email:
                    type: string
                    label: toro.ui.email
                name:
                    type: string
                    label: toro.ui.name
                    options:
                        fields: [firstName, lastName]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
