sylius_grid:
    grids:
        toro_admin_core_post:
            driver:
                name: doctrine/orm
                options:
                    class: "%toro.model.post.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments:
                            - "%locale%"
                            - $criteria
            sorting:
                createdAt: desc

            filters:
                title:
                    type: string
                    label: Search title
                    options:
                        default: true
                        fields: [translation.title, translation.description]
                state:
                    type: string
                    label: Search state
                taxon:
                    type: string
                    options:
                        fields: [taxon]
                tagId:
                    type: string
                    options:
                        fields: [tag.id]
                flaggedTypeId:
                    type: string
                    options:
                        fields: [flaggedType.id]

            fields:
                flagged:
                    type: twig
                    label: "Flaggeds"
                    path: .
                    options:
                        template: "@ToroCore/Post/Field/flagged.html.twig"
                type:
                    type: twig
                    label: "Type"
                    options:
                        template: "@ToroCore/Post/Field/type.html.twig"
                published:
                    type: twig
                    label: Published
                    options:
                        template: "@ToroAdmin/Grid/Field/yesNo.html.twig"
                title:
                    type: string
                    label: Title
                createdAt:
                    type: datetime
                    label: Created Date
                    sortable: ~
                    options:
                        format: d-m-Y H:i

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
