sylius_user:
    resources:
        web:
            user:
                classes:
                    model: Toro\Bundle\CoreBundle\Model\WebUser
                    form: Toro\Bundle\CoreBundle\Form\Type\User\WebUserType
                    repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\UserRepository
