sylius_resource:
    resources:
        toro.post_image_collection:
            classes:
                model: Toro\Bundle\CoreBundle\Model\PostImageCollection
                interface: Toro\Bundle\CoreBundle\Model\PostImageCollectionInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                factory: Sylius\Component\Resource\Factory\TranslatableFactory
                form: Toro\Bundle\CoreBundle\Form\Type\PostImageCollectionType
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
            translation:
                classes:
                    model: Toro\Bundle\CoreBundle\Model\PostImageCollectionTranslation
                    interface: Toro\Bundle\CoreBundle\Model\PostImageCollectionTranslationInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                    factory: Sylius\Component\Resource\Factory\Factory
                    form: Toro\Bundle\MediaBundle\Form\Type\ImageCollectionTranslationType

        toro.post_flagged:
            classes:
                model: Toro\Bundle\CoreBundle\Model\PostFlagged
                interface: Toro\Bundle\CoreBundle\Model\PostFlaggedInterface
                #controller: Toro\Bundle\CoreBundle\Controller\PostFlaggedController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository

        toro.post_flagged_type:
            classes:
                model: Toro\Bundle\CoreBundle\Model\PostFlaggedType
                interface: Toro\Bundle\CoreBundle\Model\PostFlaggedTypeInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                factory: Sylius\Component\Resource\Factory\Factory
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form: Toro\Bundle\CoreBundle\Form\Type\PostFlaggedTypeType
